
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
// import process from "process";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  // engine: "classic",
  datasource: {
    // url: env("DATABASE_URL"),
    url: process.env["DATABASE_URL"] || "",
  },
});
